<a href="https://colab.research.google.com/github/maumas201/Ci-ncia_Dados_Apedizagem_Maquina/blob/main/Capitulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nome: Maurício Rafael| UDF| Sistemas de Informação| CiEncia de dados

Python para Ciência de Dados

Manipulação de Dados Tabulares com Pandas - Funções Básicas

Tipos de Dados com Pandas

Renomeando Colunas

Selecionando Linhas e Colunas

Adicionando e Removendo Colunas

Operações Básicas - Consultas

Operações Básicas - Ordenação

Operações Básicas - Combinando DataFrames

Operações Básicas - Salvando DataFrames

In [3]:
import pandas as pd

In [4]:
cidades = pd.DataFrame(
    [
        ['Paraná', 'Londrina', 575377, 1356.00],
        ['São Paulo', 'São Carlos', 254484, 1508.00],
        ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
        ['Paraná', 'Curitiba', 1963726, 2293.00],
        ['São Paulo', 'Campinas', 1223237, 1710.00]
    ], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'])
cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [8]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [9]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

      Estado    Cidade  Habitantes  Salário-Médio
3     Paraná  Curitiba     1963726         2293.0
4  São Paulo  Campinas     1223237         1710.0

In [10]:
cidades.shape # Retorna uma tupla com o número de linhas e colunas

(5, 4)

In [11]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   Habitantes     5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [12]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

Index(['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'], dtype='object')

In [13]:
cidades['Salário-Médio'].describe() # Retorna um objeto DataFrame com as medidas estatísticas para cada coluna

count       5.000000
mean     1733.000000
std       357.459089
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1798.000000
max      2293.000000
Name: Salário-Médio, dtype: float64