<a href="https://colab.research.google.com/github/maumas201/Ci-ncia_Dados_Apedizagem_Maquina/blob/main/ciencia_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 02/09  II – Análise e Ciência de Dados
- Visualização e interpretação de dados
- Aula prática + resolução colaborativa de  problemas
- Criar gráficos e interpretar informações obtidas dos dados
- Dashboard ou conjunto de visualizações comentadas


Maurício Rafael  | SI |Referência
CARVALHO, André Carlos de; MENEZES, Angelo; BONIDIA, Robson. Ciência de Dados — Fundamentos e
Aplicações. Capítulo “Python para Ciência de Dados”. Disponível em: https://bonidia.github.io/cd-fundamentos/cp2.html. Acesso em: 2 set. 2026.

Exercício 1 — Reconhecendo o dataset
Enunciado: Carregue o CSV. Exiba as cinco primeiras e as três últimas linhas. Informe dimensões e nomes das
colunas.
Objetivo de aprendizagem: Carregar e reconhecer estrutura.
Dados necessários: chamados_suporte_ti.csv / DataFrame df.
Comandos/conceitos: read_csv, head, tail, shape, columns.
Nível: Básico.
Resposta esperada: Código e frase sobre dimensões/variáveis.


Exercício 2 — Tipos, ausências e resumo
Enunciado: Use info() e describe(). Quais colunas têm ausências? Qual tempo merece investigação por ser
muito maior que a maioria?
Objetivo de aprendizagem: Avaliar tipos, completude e estatísticas.
Dados necessários: chamados_suporte_ti.csv / DataFrame df.
Comandos/conceitos: info, describe.
Nível: Básico.
Resposta esperada: Ausências e possível outlier identificados.


Exercício 3 — Seleção
Enunciado: Selecione id, setor, prioridade e status; com posições, mostre cinco linhas e quatro colunas;
explique seleção versus filtro.
Objetivo de aprendizagem: Distinguir projeção, recorte e filtro.
Dados necessários: chamados_suporte_ti.csv / DataFrame df.
Comandos/conceitos: listas de colunas, iloc.
Nível: Básico.
Resposta esperada: Dois recortes e explicação.


Exercício 4 — Filtros de negócio
Enunciado: Encontre prioridade Alta; resolvidos acima de 24 h; Rede ou Acesso. Conte cada resultado.
Objetivo de aprendizagem: Construir máscaras booleanas.
Dados necessários: chamados_suporte_ti.csv / DataFrame df.
Comandos/conceitos: comparação, &, isin, shape.
Nível: Intermediário.
Resposta esperada: Três filtros, contagens e interpretação.


Exercício 5 — Transformação e resumo
Enunciado: Converta a data, crie tempo_dias e calcule tempo médio por categoria em ordem decrescente.
Interprete a maior média.
Sistemas de Informação • Ciência de Dados • Pandas
Objetivo de aprendizagem: Transformar, agregar e interpretar.
Dados necessários: chamados_suporte_ti.csv / DataFrame df.
Comandos/conceitos: to_datetime, divisão, groupby, mean, sort_values.
Nível: Intermediário.
Resposta esperada: Coluna, médias e ressalva sobre outlier.


7. Atividade final — Desafio “Painel de atenção do suporte”
SLA: Crítica = 4 h; Alta = 8 h; Média = 24 h; Baixa = 48 h. A dupla deverá identificar onde o suporte precisa de
atenção.
• Inspecionar shape, info() e ao menos uma estatística.
• Selecionar as colunas relevantes e filtrar chamados resolvidos.
• Criar limite_sla_horas e dentro_sla.
• Calcular quantidade e percentual dentro/fora do SLA.
• Calcular tempo médio por categoria.
• Concluir em 3–5 linhas com duas evidências numéricas e uma recomendação

In [1]:
import pandas as pd
prioridades = pd.Series(["Alta", "Média", "Baixa"], name="prioridade")
exemplo = pd.DataFrame({"id": ["CH001", "CH002"], "tempo": [3.5, 12.0]})

In [3]:
df = pd.read_csv("chamados_suporte_ti.csv")
df.head()
df.tail(3)
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_chamado             18 non-null     object
 1   data_abertura          18 non-null     object
 2   setor                  18 non-null     object
 3   categoria              18 non-null     object
 4   prioridade             18 non-null     object
 5   status                 18 non-null     object
 6   tempo_resolucao_horas  16 non-null     float64
 7   satisfacao             16 non-null     float64
 8   reaberto               18 non-null     object
 9   analista               18 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.5+ KB

       tempo_resolucao_horas  satisfacao
count              16.000000   16.000000
mean               23.000000    3.625000
std                29.648496    1.310216
min                 2.000000    1.000000
25%                 6.750000    2.750000
50%                13.000000    4.000000
75%                22.500000    5.000000
max               120.000000    5.000000

In [4]:
import pandas as pd
df = pd.read_csv("chamados_suporte_ti.csv")
df.head()
df.tail(3)
print(df.shape)
print(df.columns.tolist())

(18, 10)
['id_chamado', 'data_abertura', 'setor', 'categoria', 'prioridade', 'status', 'tempo_resolucao_horas', 'satisfacao', 'reaberto', 'analista']

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_chamado             18 non-null     object
 1   data_abertura          18 non-null     object
 2   setor                  18 non-null     object
 3   categoria              18 non-null     object
 4   prioridade             18 non-null     object
 5   status                 18 non-null     object
 6   tempo_resolucao_horas  16 non-null     float64
 7   satisfacao             16 non-null     float64
 8   reaberto               18 non-null     object
 9   analista               18 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.5+ KB

       tempo_resolucao_horas  satisfacao
count              16.000000   16.000000
mean               23.000000    3.625000
std                29.648496    1.310216
min                 2.000000    1.000000
25%                 6.750000    2.750000
50%                13.000000    4.000000
75%                22.500000    5.000000
max               120.000000    5.000000

In [6]:
recorte = df[["id_chamado", "setor", "prioridade", "status"]]
posicional = df.iloc[0:5, 0:4]
display(recorte.head(), posicional)

  id_chamado       setor prioridade        status
0      CH001  Financeiro       Alta     Resolvido
1      CH002   Acadêmico      Média     Resolvido
2      CH003  Biblioteca      Baixa     Resolvido
3      CH004  Financeiro    Crítica     Resolvido
4      CH005          RH      Média  Em andamento

  id_chamado data_abertura       setor        categoria
0      CH001    2026-08-20  Financeiro           Acesso
1      CH002    2026-08-20   Acadêmico    Sistema lento
2      CH003    2026-08-21  Biblioteca       Impressora
3      CH004    2026-08-21  Financeiro  Erro de sistema
4      CH005    2026-08-22          RH           Acesso

In [7]:
altos = df[df["prioridade"] == "Alta"]
lentos = df[(df["status"] == "Resolvido") & (df["tempo_resolucao_horas"] > 24)]
rede_acesso = df[df["categoria"].isin(["Rede", "Acesso"])]
print(altos.shape[0], lentos.shape[0], rede_acesso.shape[0])

4 4 7

In [8]:
df["data_abertura"] = pd.to_datetime(df["data_abertura"])
df["tempo_dias"] = df["tempo_resolucao_horas"] / 24
media = df.groupby("categoria")["tempo_resolucao_horas"].mean().sort_values(ascending=False)
media

categoria
Sistema lento      47.750000
Impressora         30.000000
Acesso             21.833333
Hardware           18.000000
Rede               11.166667
Erro de sistema     4.000000
Name: tempo_resolucao_horas, dtype: float64

In [9]:
import pandas as pd
df = pd.read_csv("chamados_suporte_ti.csv")
colunas = ["id_chamado", "categoria", "prioridade", "status",
"tempo_resolucao_horas", "satisfacao", "reaberto"]
analise = df[colunas].copy()
resolvidos = analise[analise["status"] == "Resolvido"].copy()
limites = {"Crítica": 4, "Alta": 8, "Média": 24, "Baixa": 48}
resolvidos["limite_sla_horas"] = resolvidos["prioridade"].map(limites)
resolvidos["dentro_sla"] = resolvidos["tempo_resolucao_horas"] <= resolvidos["limite_sla_horas"]
contagem = resolvidos["dentro_sla"].value_counts()
percentual = resolvidos["dentro_sla"].value_counts(normalize=True).mul(100).round(1)
media = resolvidos.groupby("categoria")["tempo_resolucao_horas"].mean().sort_values(ascending=False).round(2)
display(contagem, percentual, media)

dentro_sla
True     11
False     5
Name: count, dtype: int64

dentro_sla
True     68.8
False    31.2
Name: proportion, dtype: float64

categoria
Sistema lento      47.75
Impressora         30.00
Acesso             21.83
Hardware           18.00
Rede               11.17
Erro de sistema     4.00
Name: tempo_resolucao_horas, dtype: float64